Fresh pull request for sorting algorithms
codeiiest-dev/Algorithms pull request #26
Opened 2020-11-24 13:29 UTC by Ahel2000

# Description
Add insertion sort, selection sort and merge sort.

Issue #5 

## Type of change

Please delete options that are not relevant.

- [x] Added Algorithm
- [x] Folder Structure

# Added to SUMMARY.md (delete section if not needed)?

Have you added the page to SUMMARY.md if this is a new page and not a fix?

- [x] Yes
- [ ] No

2020-11-24 16:32 UTC, sadn1ck commented
@Ahel2000 do we need the .java files? You already added code in the markdown files. @arnabsen1729 opinion?

2020-11-25 12:21 UTC, arnabsen1729 commented on src/SortingAlgorithms/InsertionSort/Insertion.java
> +}
Remove this file.

2020-11-25 12:22 UTC, arnabsen1729 commented on src/SortingAlgorithms/InsertionSort/insertion.md
> +---------------
use <hr>

2020-11-25 12:22 UTC, arnabsen1729 commented on src/SortingAlgorithms/InsertionSort/insertion.md
> +-----------
here as well remove these with `<hr>`

2020-11-25 12:23 UTC, arnabsen1729 commented on src/SortingAlgorithms/MergeSort/Merge.java
> +}
File not needed

2020-11-25 14:41 UTC, Ahel2000 commented
I have made the changes @arnabsen1729

2020-11-27 04:16 UTC, sadn1ck commented on src/SortingAlgorithms/InsertionSort/insertion.md
> +### Code For Insertion Sort
Add some space here, markdown shenanigans

2020-11-27 04:18 UTC, sadn1ck requested changes
Check the comments, then I will merge. @arnabsen1729 have a look as well

2020-11-27 04:30 UTC, sadn1ck approved these changes
LGTM

2020-11-27 04:31 UTC, merged

2020-11-27 04:33 UTC, sadn1ck commented
@allcontributors add @Ahel2000 for contributing to documentation